### ISSUE TITLE
Bug in attacks base.py

### ISSUE THREAD

**Issue by FZU-LW** [THUYimingLi/BackdoorBox#61]
当我想使用多 GPU 时，我将 scheduler 做了如下改动：`'CUDA_VISIBLE_DEVICES': '0, 1',  'GPU_num': 2`，然后出现了如下错误：
```
Traceback (most recent call last):
  File "example.py", line 146, in <module>
    badnets.train(schedule)
  File "/BackdoorBox-main/core/attacks/base.py", line 167, in train
    self.model = self.model.to(device)
UnboundLocalError: local variable 'device' referenced before assignment
```
我认为这个错误出现在使用多个 GPU 时，没有将 device 指定为 GPU，导致程序后续在移动数据到指定设备上时，发现之前并没有指定 device。
我的解决方案是添加指定 device 的一行代码，截图如下：
![1692158471099](https://github.com/THUYimingLi/BackdoorBox/assets/50572685/2a66d31c-cdc4-468b-8970-d8de9fed0988)

我不知道这样的解决方案是否是最佳的。我期待你们修复这个 bug 🥂

**Comment by THUYimingLi** [comment]
感谢建议，我们将在近期review这个修改！

**Comment by yamengxi** [comment]
@FZU-LW 
感谢你提出的问题，我们的旧版本不支持多卡训练。
为了支持多卡训练，我们更新了一个版本，可以实现多卡并行训练（DP），具体的使用方法可以参考样例BackdoorBox/tests/test_BadNets_with_multi_gpus.py
